spring.application.name=midtier



spring.security.oauth2.client.registration.google.scope=email,profile
# spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
spring.security.oauth2.client.registration.google.client-id=531654488309-l67rmm2ga2kvdvr5ornmrel3uohdrihb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

# JWT Configuration

jwt.expiration=86400

jwt.secret=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

jwt.client-id=531654488309-l67rmm2ga2kvdvr5ornmrel3uohdrihb.apps.googleusercontent.com
